// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupSessions = `-- name: CleanupSessions :execrows
with cleanup_candidate as (
    select active_session.id
    from session as active_session
    where active_session.expires_at <= clock_timestamp()
        or active_session.revoked_at is not null
    order by active_session.expires_at, active_session.id
    limit 500
    for update of active_session skip locked
)
delete from session as active_session
using cleanup_candidate
where active_session.id = cleanup_candidate.id
`

func (q *Queries) CleanupSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthSession = `-- name: CreateAuthSession :exec
insert into session (id, user_id, expires_at, last_seen_at, created_at)
values (
    $1::text,
    $2::text::uuid,
    $3::timestamptz,
    clock_timestamp(),
    clock_timestamp()
)
`

type CreateAuthSessionParams struct {
	SessionID string             `json:"session_id"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession, arg.SessionID, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteAuthLoginAttempt = `-- name: DeleteAuthLoginAttempt :execrows
delete from auth_login_attempt
where username_hash = $1
`

func (q *Queries) DeleteAuthLoginAttempt(ctx context.Context, usernameHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthLoginAttempt, usernameHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleAuthLoginAttempts = `-- name: DeleteStaleAuthLoginAttempts :execrows
with database_clock as (
    select clock_timestamp() as value
), stale_attempt as (
    select attempt.username_hash
    from auth_login_attempt as attempt
    cross join database_clock
    where attempt.updated_at <= database_clock.value - interval '15 minutes'
        and (attempt.blocked_until is null or attempt.blocked_until <= database_clock.value)
    order by attempt.updated_at, attempt.username_hash
    limit $1::bigint
    for update of attempt skip locked
)
delete from auth_login_attempt as attempt
using stale_attempt
where attempt.username_hash = stale_attempt.username_hash
`

func (q *Queries) DeleteStaleAuthLoginAttempts(ctx context.Context, batchSize int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleAuthLoginAttempts, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureAuthLoginAttempt = `-- name: EnsureAuthLoginAttempt :exec
insert into auth_login_attempt (
    username_hash,
    failed_attempts,
    window_started_at,
    blocked_until,
    updated_at
)
values ($1, 0, clock_timestamp(), null, clock_timestamp())
on conflict (username_hash) do nothing
`

func (q *Queries) EnsureAuthLoginAttempt(ctx context.Context, usernameHash string) error {
	_, err := q.db.Exec(ctx, ensureAuthLoginAttempt, usernameHash)
	return err
}

const getAuthLoginAttemptForUpdate = `-- name: GetAuthLoginAttemptForUpdate :one
select
    username_hash,
    failed_attempts,
    window_started_at,
    blocked_until,
    updated_at,
    clock_timestamp()::timestamptz as database_time
from auth_login_attempt
where username_hash = $1
for update
`

type GetAuthLoginAttemptForUpdateRow struct {
	UsernameHash    string             `json:"username_hash"`
	FailedAttempts  int16              `json:"failed_attempts"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DatabaseTime    pgtype.Timestamptz `json:"database_time"`
}

func (q *Queries) GetAuthLoginAttemptForUpdate(ctx context.Context, usernameHash string) (GetAuthLoginAttemptForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthLoginAttemptForUpdate, usernameHash)
	var i GetAuthLoginAttemptForUpdateRow
	err := row.Scan(
		&i.UsernameHash,
		&i.FailedAttempts,
		&i.WindowStartedAt,
		&i.BlockedUntil,
		&i.UpdatedAt,
		&i.DatabaseTime,
	)
	return i, err
}

const getAuthUserByUsername = `-- name: GetAuthUserByUsername :one
select
    app_user.id::text as user_id,
    app_user.username,
    app_user.nickname,
    app_user.password_hash,
    app_user.status,
    user_group.key as group_key,
    user_group.permissions
from app_user
join user_group on user_group.id = app_user.group_id
where app_user.username = $1 and app_user.deleted_at is null
`

type GetAuthUserByUsernameRow struct {
	UserID       string      `json:"user_id"`
	Username     string      `json:"username"`
	Nickname     string      `json:"nickname"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Status       string      `json:"status"`
	GroupKey     string      `json:"group_key"`
	Permissions  []byte      `json:"permissions"`
}

func (q *Queries) GetAuthUserByUsername(ctx context.Context, username string) (GetAuthUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByUsername, username)
	var i GetAuthUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Nickname,
		&i.PasswordHash,
		&i.Status,
		&i.GroupKey,
		&i.Permissions,
	)
	return i, err
}

const recordAuthLoginFailure = `-- name: RecordAuthLoginFailure :one
with database_clock as (
    select clock_timestamp() as value
)
update auth_login_attempt as attempt
set failed_attempts = case
        when attempt.window_started_at <= database_clock.value - interval '15 minutes' then 1
        else attempt.failed_attempts + 1
    end,
    window_started_at = case
        when attempt.window_started_at <= database_clock.value - interval '15 minutes' then database_clock.value
        else attempt.window_started_at
    end,
    blocked_until = case
        when attempt.window_started_at <= database_clock.value - interval '15 minutes' then null
        when attempt.failed_attempts + 1 >= 10 then database_clock.value + interval '15 minutes'
        else attempt.blocked_until
    end,
    updated_at = database_clock.value
from database_clock
where attempt.username_hash = $1
returning attempt.username_hash, attempt.failed_attempts, attempt.window_started_at, attempt.blocked_until, attempt.updated_at
`

func (q *Queries) RecordAuthLoginFailure(ctx context.Context, usernameHash string) (AuthLoginAttempt, error) {
	row := q.db.QueryRow(ctx, recordAuthLoginFailure, usernameHash)
	var i AuthLoginAttempt
	err := row.Scan(
		&i.UsernameHash,
		&i.FailedAttempts,
		&i.WindowStartedAt,
		&i.BlockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}
