// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultShortLinkDomain = `-- name: ClearDefaultShortLinkDomain :exec
update domain set is_default = false,
    updated_at = greatest(clock_timestamp(), updated_at + interval '1 microsecond')
where is_default = true and purpose = 'short_link'
`

func (q *Queries) ClearDefaultShortLinkDomain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultShortLinkDomain)
	return err
}

const createDomain = `-- name: CreateDomain :one
insert into domain (id, host, display_name, purpose, enabled, is_default, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
returning id, host, display_name, purpose, enabled, is_default, created_at, updated_at
`

type CreateDomainParams struct {
	ID          pgtype.UUID `json:"id"`
	Host        string      `json:"host"`
	DisplayName string      `json:"display_name"`
	Purpose     string      `json:"purpose"`
	Enabled     bool        `json:"enabled"`
	IsDefault   bool        `json:"is_default"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.ID,
		arg.Host,
		arg.DisplayName,
		arg.Purpose,
		arg.Enabled,
		arg.IsDefault,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DisplayName,
		&i.Purpose,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomainGrants = `-- name: DeleteDomainGrants :exec
delete from domain_user_group where domain_id = $1
`

func (q *Queries) DeleteDomainGrants(ctx context.Context, domainID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDomainGrants, domainID)
	return err
}

const deleteManagedDomain = `-- name: DeleteManagedDomain :execrows
delete from domain where domain.id = $1 and domain.purpose = 'short_link' and domain.is_default = false
    and domain.updated_at = $2 and not exists(select 1 from short_link where short_link.domain_id = $1)
`

type DeleteManagedDomainParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeleteManagedDomain(ctx context.Context, arg DeleteManagedDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManagedDomain, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const domainHasReferences = `-- name: DomainHasReferences :one
select exists(select 1 from short_link where domain_id = $1)
`

func (q *Queries) DomainHasReferences(ctx context.Context, domainID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, domainHasReferences, domainID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDefaultShortLinkDomain = `-- name: GetDefaultShortLinkDomain :one
select id, host, display_name, purpose, enabled, is_default, created_at, updated_at
from domain
where enabled = true and is_default = true
limit 1
`

func (q *Queries) GetDefaultShortLinkDomain(ctx context.Context) (Domain, error) {
	row := q.db.QueryRow(ctx, getDefaultShortLinkDomain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DisplayName,
		&i.Purpose,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGrantedShortLinkDomainForCreate = `-- name: GetGrantedShortLinkDomainForCreate :one
select domain.id, domain.host
from domain
join domain_user_group on domain_user_group.domain_id = domain.id
join user_group on user_group.id = domain_user_group.user_group_id
where domain.enabled and domain.purpose = 'short_link'
  and user_group.key = $1 and user_group.builtin
  and user_group.permissions ? 'short_link:create'
  and user_group.permissions ? $2::text
  and (($3::boolean and domain.is_default)
       or (not $3::boolean and not domain.is_default
           and domain.id = $4::uuid))
for share of domain, domain_user_group, user_group
`

type GetGrantedShortLinkDomainForCreateParams struct {
	GroupKey           string      `json:"group_key"`
	RequiredPermission string      `json:"required_permission"`
	UseDefault         bool        `json:"use_default"`
	DomainID           pgtype.UUID `json:"domain_id"`
}

type GetGrantedShortLinkDomainForCreateRow struct {
	ID   pgtype.UUID `json:"id"`
	Host string      `json:"host"`
}

func (q *Queries) GetGrantedShortLinkDomainForCreate(ctx context.Context, arg GetGrantedShortLinkDomainForCreateParams) (GetGrantedShortLinkDomainForCreateRow, error) {
	row := q.db.QueryRow(ctx, getGrantedShortLinkDomainForCreate,
		arg.GroupKey,
		arg.RequiredPermission,
		arg.UseDefault,
		arg.DomainID,
	)
	var i GetGrantedShortLinkDomainForCreateRow
	err := row.Scan(&i.ID, &i.Host)
	return i, err
}

const getManagedDomainForUpdate = `-- name: GetManagedDomainForUpdate :one
select id, host, display_name, purpose, enabled, is_default, created_at, updated_at
from domain where id = $1 and purpose = 'short_link' for update
`

func (q *Queries) GetManagedDomainForUpdate(ctx context.Context, id pgtype.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getManagedDomainForUpdate, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DisplayName,
		&i.Purpose,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShortLinkDomainByID = `-- name: GetShortLinkDomainByID :one
select id, host from domain where id = $1
`

type GetShortLinkDomainByIDRow struct {
	ID   pgtype.UUID `json:"id"`
	Host string      `json:"host"`
}

func (q *Queries) GetShortLinkDomainByID(ctx context.Context, id pgtype.UUID) (GetShortLinkDomainByIDRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkDomainByID, id)
	var i GetShortLinkDomainByIDRow
	err := row.Scan(&i.ID, &i.Host)
	return i, err
}

const insertDomainGrant = `-- name: InsertDomainGrant :execrows
insert into domain_user_group (domain_id, user_group_id)
select $1, user_group.id from user_group where user_group.key = $2 and user_group.builtin = true and user_group.key in ('user', 'admin')
`

type InsertDomainGrantParams struct {
	DomainID pgtype.UUID `json:"domain_id"`
	Key      string      `json:"key"`
}

func (q *Queries) InsertDomainGrant(ctx context.Context, arg InsertDomainGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDomainGrant, arg.DomainID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAvailableShortLinkDomains = `-- name: ListAvailableShortLinkDomains :many
select domain.id, domain.host, domain.display_name, domain.is_default
from domain
join domain_user_group on domain_user_group.domain_id = domain.id
join user_group on user_group.id = domain_user_group.user_group_id
where user_group.key = $1
  and user_group.builtin = true
  and domain.enabled = true and domain.purpose = 'short_link'
  and ((domain.is_default and $2::boolean)
       or (not domain.is_default and $3::boolean))
order by domain.is_default desc, domain.created_at, domain.id
`

type ListAvailableShortLinkDomainsParams struct {
	GroupKey    string `json:"group_key"`
	CanDefault  bool   `json:"can_default"`
	CanAssigned bool   `json:"can_assigned"`
}

type ListAvailableShortLinkDomainsRow struct {
	ID          pgtype.UUID `json:"id"`
	Host        string      `json:"host"`
	DisplayName string      `json:"display_name"`
	IsDefault   bool        `json:"is_default"`
}

func (q *Queries) ListAvailableShortLinkDomains(ctx context.Context, arg ListAvailableShortLinkDomainsParams) ([]ListAvailableShortLinkDomainsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableShortLinkDomains, arg.GroupKey, arg.CanDefault, arg.CanAssigned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableShortLinkDomainsRow{}
	for rows.Next() {
		var i ListAvailableShortLinkDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.DisplayName,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainGrantKeys = `-- name: ListDomainGrantKeys :many
select user_group.key
from domain_user_group
join user_group on user_group.id = domain_user_group.user_group_id
where domain_user_group.domain_id = $1
order by user_group.key
`

func (q *Queries) ListDomainGrantKeys(ctx context.Context, domainID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDomainGrantKeys, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainHosts = `-- name: ListDomainHosts :many
select id, host from domain
`

type ListDomainHostsRow struct {
	ID   pgtype.UUID `json:"id"`
	Host string      `json:"host"`
}

func (q *Queries) ListDomainHosts(ctx context.Context) ([]ListDomainHostsRow, error) {
	rows, err := q.db.Query(ctx, listDomainHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainHostsRow{}
	for rows.Next() {
		var i ListDomainHostsRow
		if err := rows.Scan(&i.ID, &i.Host); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedDomains = `-- name: ListManagedDomains :many
select domain.id, domain.host, domain.display_name, domain.purpose, domain.enabled,
       domain.is_default, domain.created_at, domain.updated_at,
       exists(select 1 from short_link where short_link.domain_id = domain.id) as referenced
from domain
where domain.purpose = 'short_link'
order by domain.is_default desc, domain.created_at, domain.id
`

type ListManagedDomainsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Host        string             `json:"host"`
	DisplayName string             `json:"display_name"`
	Purpose     string             `json:"purpose"`
	Enabled     bool               `json:"enabled"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Referenced  bool               `json:"referenced"`
}

func (q *Queries) ListManagedDomains(ctx context.Context) ([]ListManagedDomainsRow, error) {
	rows, err := q.db.Query(ctx, listManagedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedDomainsRow{}
	for rows.Next() {
		var i ListManagedDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.DisplayName,
			&i.Purpose,
			&i.Enabled,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Referenced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeDefaultShortLinkDomain = `-- name: MakeDefaultShortLinkDomain :one
update domain set is_default = true,
    updated_at = greatest(clock_timestamp(), updated_at + interval '1 microsecond')
where domain.id = $1 and domain.enabled = true and domain.purpose = 'short_link' and domain.updated_at = $2
returning domain.id, domain.host, domain.display_name, domain.purpose, domain.enabled,
    domain.is_default, domain.created_at, domain.updated_at
`

type MakeDefaultShortLinkDomainParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MakeDefaultShortLinkDomain(ctx context.Context, arg MakeDefaultShortLinkDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, makeDefaultShortLinkDomain, arg.ID, arg.UpdatedAt)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DisplayName,
		&i.Purpose,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagedDomain = `-- name: UpdateManagedDomain :one
update domain
set host = $2, display_name = $3, enabled = $4,
    updated_at = greatest(clock_timestamp(), updated_at + interval '1 microsecond')
where domain.id = $1 and domain.purpose = 'short_link' and domain.updated_at = $5
returning domain.id, domain.host, domain.display_name, domain.purpose, domain.enabled,
    domain.is_default, domain.created_at, domain.updated_at
`

type UpdateManagedDomainParams struct {
	ID          pgtype.UUID        `json:"id"`
	Host        string             `json:"host"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateManagedDomain(ctx context.Context, arg UpdateManagedDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateManagedDomain,
		arg.ID,
		arg.Host,
		arg.DisplayName,
		arg.Enabled,
		arg.UpdatedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DisplayName,
		&i.Purpose,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
