// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one
insert into domain (id, host, display_name, purpose, enabled, is_default, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
returning id, host, display_name, purpose, enabled, is_default, created_at, updated_at
`

type CreateDomainParams struct {
	ID          pgtype.UUID `json:"id"`
	Host        string      `json:"host"`
	DisplayName string      `json:"display_name"`
	Purpose     string      `json:"purpose"`
	Enabled     bool        `json:"enabled"`
	IsDefault   bool        `json:"is_default"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.ID,
		arg.Host,
		arg.DisplayName,
		arg.Purpose,
		arg.Enabled,
		arg.IsDefault,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DisplayName,
		&i.Purpose,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultShortLinkDomain = `-- name: GetDefaultShortLinkDomain :one
select id, host, display_name, purpose, enabled, is_default, created_at, updated_at
from domain
where enabled = true and is_default = true
limit 1
`

func (q *Queries) GetDefaultShortLinkDomain(ctx context.Context) (Domain, error) {
	row := q.db.QueryRow(ctx, getDefaultShortLinkDomain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DisplayName,
		&i.Purpose,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
