// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShortLinkEvent = `-- name: CreateShortLinkEvent :exec
insert into short_link_event (id, short_link_id, event_type, referrer_host, device_type, country_code, created_at)
values ($1, $2, $3, $4, $5, $6, now())
`

type CreateShortLinkEventParams struct {
	ID           pgtype.UUID `json:"id"`
	ShortLinkID  pgtype.UUID `json:"short_link_id"`
	EventType    string      `json:"event_type"`
	ReferrerHost pgtype.Text `json:"referrer_host"`
	DeviceType   pgtype.Text `json:"device_type"`
	CountryCode  pgtype.Text `json:"country_code"`
}

func (q *Queries) CreateShortLinkEvent(ctx context.Context, arg CreateShortLinkEventParams) error {
	_, err := q.db.Exec(ctx, createShortLinkEvent,
		arg.ID,
		arg.ShortLinkID,
		arg.EventType,
		arg.ReferrerHost,
		arg.DeviceType,
		arg.CountryCode,
	)
	return err
}

const getShortLinkAnalyticsSummary = `-- name: GetShortLinkAnalyticsSummary :one
select count(*)::bigint as visit_count,
    count(*) filter (where created_at >= current_date)::bigint as today_visit_count,
    max(created_at)::timestamptz as last_visited_at
from short_link_event
where short_link_id = $1 and event_type = 'redirect_response_sent'
`

type GetShortLinkAnalyticsSummaryRow struct {
	VisitCount      int64              `json:"visit_count"`
	TodayVisitCount int64              `json:"today_visit_count"`
	LastVisitedAt   pgtype.Timestamptz `json:"last_visited_at"`
}

func (q *Queries) GetShortLinkAnalyticsSummary(ctx context.Context, shortLinkID pgtype.UUID) (GetShortLinkAnalyticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkAnalyticsSummary, shortLinkID)
	var i GetShortLinkAnalyticsSummaryRow
	err := row.Scan(&i.VisitCount, &i.TodayVisitCount, &i.LastVisitedAt)
	return i, err
}

const listShortLinkCountryStats = `-- name: ListShortLinkCountryStats :many
with grouped as (
    select coalesce(nullif(country_code, ''), 'unknown') as value, count(*)::bigint as visit_count
    from short_link_event
    where short_link_id = $1 and event_type = 'redirect_response_sent'
    group by 1
), ranked as (
    select value, visit_count, row_number() over (order by visit_count desc, value asc) as rank
    from grouped
)
select case when rank <= 10 then value else 'other' end as value, sum(visit_count)::bigint as visit_count
from ranked
group by 1
order by visit_count desc, value asc
`

type ListShortLinkCountryStatsRow struct {
	Value      string `json:"value"`
	VisitCount int64  `json:"visit_count"`
}

func (q *Queries) ListShortLinkCountryStats(ctx context.Context, shortLinkID pgtype.UUID) ([]ListShortLinkCountryStatsRow, error) {
	rows, err := q.db.Query(ctx, listShortLinkCountryStats, shortLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortLinkCountryStatsRow{}
	for rows.Next() {
		var i ListShortLinkCountryStatsRow
		if err := rows.Scan(&i.Value, &i.VisitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortLinkDailyVisits = `-- name: ListShortLinkDailyVisits :many
with days as (
    select generate_series(current_date - interval '6 days', current_date, interval '1 day')::date as day
)
select days.day,
    count(short_link_event.id)::bigint as visit_count
from days
left join short_link_event
    on short_link_event.short_link_id = $1
    and short_link_event.event_type = 'redirect_response_sent'
    and short_link_event.created_at >= days.day
    and short_link_event.created_at < days.day + interval '1 day'
group by days.day
order by days.day
`

type ListShortLinkDailyVisitsRow struct {
	Day        pgtype.Date `json:"day"`
	VisitCount int64       `json:"visit_count"`
}

func (q *Queries) ListShortLinkDailyVisits(ctx context.Context, shortLinkID pgtype.UUID) ([]ListShortLinkDailyVisitsRow, error) {
	rows, err := q.db.Query(ctx, listShortLinkDailyVisits, shortLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortLinkDailyVisitsRow{}
	for rows.Next() {
		var i ListShortLinkDailyVisitsRow
		if err := rows.Scan(&i.Day, &i.VisitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortLinkDeviceStats = `-- name: ListShortLinkDeviceStats :many
with grouped as (
    select coalesce(nullif(device_type, ''), 'unknown') as value, count(*)::bigint as visit_count
    from short_link_event
    where short_link_id = $1 and event_type = 'redirect_response_sent'
    group by 1
), ranked as (
    select value, visit_count, row_number() over (order by visit_count desc, value asc) as rank
    from grouped
)
select case when rank <= 10 then value else 'other' end as value, sum(visit_count)::bigint as visit_count
from ranked
group by 1
order by visit_count desc, value asc
`

type ListShortLinkDeviceStatsRow struct {
	Value      string `json:"value"`
	VisitCount int64  `json:"visit_count"`
}

func (q *Queries) ListShortLinkDeviceStats(ctx context.Context, shortLinkID pgtype.UUID) ([]ListShortLinkDeviceStatsRow, error) {
	rows, err := q.db.Query(ctx, listShortLinkDeviceStats, shortLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortLinkDeviceStatsRow{}
	for rows.Next() {
		var i ListShortLinkDeviceStatsRow
		if err := rows.Scan(&i.Value, &i.VisitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortLinkReferrerStats = `-- name: ListShortLinkReferrerStats :many
with grouped as (
    select coalesce(nullif(referrer_host, ''), 'unknown') as value, count(*)::bigint as visit_count
    from short_link_event
    where short_link_id = $1 and event_type = 'redirect_response_sent'
    group by 1
), ranked as (
    select value, visit_count, row_number() over (order by visit_count desc, value asc) as rank
    from grouped
)
select case when rank <= 10 then value else 'other' end as value, sum(visit_count)::bigint as visit_count
from ranked
group by 1
order by visit_count desc, value asc
`

type ListShortLinkReferrerStatsRow struct {
	Value      string `json:"value"`
	VisitCount int64  `json:"visit_count"`
}

func (q *Queries) ListShortLinkReferrerStats(ctx context.Context, shortLinkID pgtype.UUID) ([]ListShortLinkReferrerStatsRow, error) {
	rows, err := q.db.Query(ctx, listShortLinkReferrerStats, shortLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortLinkReferrerStatsRow{}
	for rows.Next() {
		var i ListShortLinkReferrerStatsRow
		if err := rows.Scan(&i.Value, &i.VisitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
