// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShortLinkEvent = `-- name: CreateShortLinkEvent :exec
insert into short_link_event (id, short_link_id, event_type, created_at)
values ($1, $2, $3, now())
`

type CreateShortLinkEventParams struct {
	ID          pgtype.UUID `json:"id"`
	ShortLinkID pgtype.UUID `json:"short_link_id"`
	EventType   string      `json:"event_type"`
}

// CreateShortLinkEvent inserts a persisted short-link access event.
func (q *Queries) CreateShortLinkEvent(ctx context.Context, arg CreateShortLinkEventParams) error {
	_, err := q.db.Exec(ctx, createShortLinkEvent, arg.ID, arg.ShortLinkID, arg.EventType)
	return err
}
