// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Nickname     string             `json:"nickname"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Status       string             `json:"status"`
	Builtin      bool               `json:"builtin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Domain struct {
	ID          pgtype.UUID        `json:"id"`
	Host        string             `json:"host"`
	DisplayName string             `json:"display_name"`
	Purpose     string             `json:"purpose"`
	Enabled     bool               `json:"enabled"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Tracks permissions added by migration 00008 for reversible rollback.
type MoeurlShortLinkConfirmationPermissionAddition struct {
	UserGroupID pgtype.UUID `json:"user_group_id"`
	Permission  string      `json:"permission"`
}

// Tracks permissions added by migration 00004 for reversible rollback.
type MoeurlShortLinkExperiencePermissionAddition struct {
	UserGroupID pgtype.UUID `json:"user_group_id"`
	Permission  string      `json:"permission"`
}

// Tracks permissions added by migration 00006 for reversible rollback.
type MoeurlShortLinkPasswordPermissionAddition struct {
	UserGroupID pgtype.UUID `json:"user_group_id"`
	Permission  string      `json:"permission"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ShortLink struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	PasswordFailedAttempts   int16              `json:"password_failed_attempts"`
	PasswordWindowStartedAt  pgtype.Timestamptz `json:"password_window_started_at"`
	PasswordBlockedUntil     pgtype.Timestamptz `json:"password_blocked_until"`
	PasswordUpdatedAt        pgtype.Timestamptz `json:"password_updated_at"`
}

type ShortLinkAccessGrant struct {
	ID          pgtype.UUID        `json:"id"`
	ShortLinkID pgtype.UUID        `json:"short_link_id"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ShortLinkEvent struct {
	ID           pgtype.UUID        `json:"id"`
	ShortLinkID  pgtype.UUID        `json:"short_link_id"`
	EventType    string             `json:"event_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ReferrerHost pgtype.Text        `json:"referrer_host"`
	DeviceType   pgtype.Text        `json:"device_type"`
	CountryCode  pgtype.Text        `json:"country_code"`
}

type SystemSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Permissions []byte             `json:"permissions"`
	Builtin     bool               `json:"builtin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
