// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Nickname     string             `json:"nickname"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Status       string             `json:"status"`
	Builtin      bool               `json:"builtin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type AuthLoginAttempt struct {
	UsernameHash    string             `json:"username_hash"`
	FailedAttempts  int16              `json:"failed_attempts"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Domain struct {
	ID          pgtype.UUID        `json:"id"`
	Host        string             `json:"host"`
	DisplayName string             `json:"display_name"`
	Purpose     string             `json:"purpose"`
	Enabled     bool               `json:"enabled"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ExternalIdentity struct {
	ProviderID  pgtype.UUID        `json:"provider_id"`
	Subject     string             `json:"subject"`
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

// Tracks permissions added by migration 00004 for reversible rollback.
type MoeurlShortLinkExperiencePermissionAddition struct {
	UserGroupID pgtype.UUID `json:"user_group_id"`
	Permission  string      `json:"permission"`
}

// Tracks permissions added by migration 00006 for reversible rollback.
type MoeurlShortLinkPasswordPermissionAddition struct {
	UserGroupID pgtype.UUID `json:"user_group_id"`
	Permission  string      `json:"permission"`
}

type OidcLoginAttempt struct {
	StateHash          []byte             `json:"state_hash"`
	ProviderID         pgtype.UUID        `json:"provider_id"`
	NonceHash          []byte             `json:"nonce_hash"`
	BrowserBindingHash []byte             `json:"browser_binding_hash"`
	VerifierCiphertext []byte             `json:"verifier_ciphertext"`
	ReturnPath         string             `json:"return_path"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type OidcProvider struct {
	ID                     pgtype.UUID        `json:"id"`
	Key                    string             `json:"key"`
	DisplayName            string             `json:"display_name"`
	IssuerUrl              string             `json:"issuer_url"`
	ClientID               string             `json:"client_id"`
	ClientSecretCiphertext []byte             `json:"client_secret_ciphertext"`
	AuthorizationEndpoint  string             `json:"authorization_endpoint"`
	TokenEndpoint          string             `json:"token_endpoint"`
	JwksUri                string             `json:"jwks_uri"`
	AllowedEmailDomains    []byte             `json:"allowed_email_domains"`
	Enabled                bool               `json:"enabled"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ShortLink struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	PasswordFailedAttempts   int16              `json:"password_failed_attempts"`
	PasswordWindowStartedAt  pgtype.Timestamptz `json:"password_window_started_at"`
	PasswordBlockedUntil     pgtype.Timestamptz `json:"password_blocked_until"`
	PasswordUpdatedAt        pgtype.Timestamptz `json:"password_updated_at"`
}

type ShortLinkAccessGrant struct {
	ID          pgtype.UUID        `json:"id"`
	ShortLinkID pgtype.UUID        `json:"short_link_id"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Tracks permissions and membership revisions added by migration 00008 for reversible rollback.
type ShortLinkConfirmationPermissionAddition struct {
	UserGroupID        pgtype.UUID `json:"user_group_id"`
	Permission         string      `json:"permission"`
	PermissionRevision int64       `json:"permission_revision"`
}

type ShortLinkEvent struct {
	ID           pgtype.UUID        `json:"id"`
	ShortLinkID  pgtype.UUID        `json:"short_link_id"`
	EventType    string             `json:"event_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ReferrerHost pgtype.Text        `json:"referrer_host"`
	DeviceType   pgtype.Text        `json:"device_type"`
	CountryCode  pgtype.Text        `json:"country_code"`
}

type SystemSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Permissions []byte             `json:"permissions"`
	Builtin     bool               `json:"builtin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
