// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOIDCLoginAttempt = `-- name: ConsumeOIDCLoginAttempt :one
delete from oidc_login_attempt
where state_hash = $1
returning state_hash, provider_id, nonce_hash, verifier_ciphertext, return_path, expires_at, created_at
`

func (q *Queries) ConsumeOIDCLoginAttempt(ctx context.Context, stateHash []byte) (OidcLoginAttempt, error) {
	row := q.db.QueryRow(ctx, consumeOIDCLoginAttempt, stateHash)
	var i OidcLoginAttempt
	err := row.Scan(
		&i.StateHash,
		&i.ProviderID,
		&i.NonceHash,
		&i.VerifierCiphertext,
		&i.ReturnPath,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countEnabledOIDCProviders = `-- name: CountEnabledOIDCProviders :one
select count(*)
from oidc_provider
where enabled and deleted_at is null
`

func (q *Queries) CountEnabledOIDCProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledOIDCProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExternalIdentity = `-- name: CreateExternalIdentity :exec
insert into external_identity (provider_id, subject, user_id, created_at, last_login_at)
values ($1, $2, $3, clock_timestamp(), clock_timestamp())
`

type CreateExternalIdentityParams struct {
	ProviderID pgtype.UUID `json:"provider_id"`
	Subject    string      `json:"subject"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, createExternalIdentity, arg.ProviderID, arg.Subject, arg.UserID)
	return err
}

const createOIDCLoginAttempt = `-- name: CreateOIDCLoginAttempt :exec
insert into oidc_login_attempt (
    state_hash,
    provider_id,
    nonce_hash,
    verifier_ciphertext,
    return_path,
    expires_at,
    created_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    clock_timestamp()
)
`

type CreateOIDCLoginAttemptParams struct {
	StateHash          []byte             `json:"state_hash"`
	ProviderID         pgtype.UUID        `json:"provider_id"`
	NonceHash          []byte             `json:"nonce_hash"`
	VerifierCiphertext []byte             `json:"verifier_ciphertext"`
	ReturnPath         string             `json:"return_path"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOIDCLoginAttempt(ctx context.Context, arg CreateOIDCLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, createOIDCLoginAttempt,
		arg.StateHash,
		arg.ProviderID,
		arg.NonceHash,
		arg.VerifierCiphertext,
		arg.ReturnPath,
		arg.ExpiresAt,
	)
	return err
}

const createOIDCProvider = `-- name: CreateOIDCProvider :one
insert into oidc_provider (
    id,
    key,
    display_name,
    issuer_url,
    client_id,
    client_secret_ciphertext,
    authorization_endpoint,
    token_endpoint,
    jwks_uri,
    allowed_email_domains,
    enabled,
    created_at,
    updated_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    clock_timestamp(),
    clock_timestamp()
)
returning id, key, display_name, issuer_url, client_id, client_secret_ciphertext, authorization_endpoint, token_endpoint, jwks_uri, allowed_email_domains, enabled, created_at, updated_at, deleted_at
`

type CreateOIDCProviderParams struct {
	ID                     pgtype.UUID `json:"id"`
	Key                    string      `json:"key"`
	DisplayName            string      `json:"display_name"`
	IssuerUrl              string      `json:"issuer_url"`
	ClientID               string      `json:"client_id"`
	ClientSecretCiphertext []byte      `json:"client_secret_ciphertext"`
	AuthorizationEndpoint  string      `json:"authorization_endpoint"`
	TokenEndpoint          string      `json:"token_endpoint"`
	JwksUri                string      `json:"jwks_uri"`
	AllowedEmailDomains    []byte      `json:"allowed_email_domains"`
	Enabled                bool        `json:"enabled"`
}

func (q *Queries) CreateOIDCProvider(ctx context.Context, arg CreateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, createOIDCProvider,
		arg.ID,
		arg.Key,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.AuthorizationEndpoint,
		arg.TokenEndpoint,
		arg.JwksUri,
		arg.AllowedEmailDomains,
		arg.Enabled,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AuthorizationEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.AllowedEmailDomains,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOIDCUser = `-- name: CreateOIDCUser :one
insert into app_user (
    id,
    username,
    password_hash,
    nickname,
    group_id,
    status,
    builtin,
    created_at,
    updated_at
)
select $1,
    $2,
    null,
    $3,
    user_group.id,
    'active',
    false,
    clock_timestamp(),
    clock_timestamp()
from user_group
where user_group.key = 'user' and user_group.builtin
returning id
`

type CreateOIDCUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Nickname string      `json:"nickname"`
}

func (q *Queries) CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createOIDCUser, arg.ID, arg.Username, arg.Nickname)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredOIDCLoginAttempts = `-- name: DeleteExpiredOIDCLoginAttempts :execrows
with expired as (
    select state_hash
    from oidc_login_attempt
    where expires_at <= clock_timestamp()
    order by expires_at, state_hash
    limit $1
    for update skip locked
)
delete from oidc_login_attempt
using expired
where oidc_login_attempt.state_hash = expired.state_hash
`

func (q *Queries) DeleteExpiredOIDCLoginAttempts(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOIDCLoginAttempts, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnabledOIDCProviderByKey = `-- name: GetEnabledOIDCProviderByKey :one
select id, key, display_name, issuer_url, client_id, client_secret_ciphertext, authorization_endpoint, token_endpoint, jwks_uri, allowed_email_domains, enabled, created_at, updated_at, deleted_at
from oidc_provider
where key = $1 and enabled and deleted_at is null
`

func (q *Queries) GetEnabledOIDCProviderByKey(ctx context.Context, key string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getEnabledOIDCProviderByKey, key)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AuthorizationEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.AllowedEmailDomains,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExternalIdentityUser = `-- name: GetExternalIdentityUser :one
select app_user.id::text as user_id,
    app_user.username,
    app_user.nickname,
    app_user.status,
    user_group.key as group_key,
    user_group.permissions
from external_identity
join app_user on app_user.id = external_identity.user_id
join user_group on user_group.id = app_user.group_id
where external_identity.provider_id = $1
  and external_identity.subject = $2
  and app_user.deleted_at is null
`

type GetExternalIdentityUserParams struct {
	ProviderID pgtype.UUID `json:"provider_id"`
	Subject    string      `json:"subject"`
}

type GetExternalIdentityUserRow struct {
	UserID      string `json:"user_id"`
	Username    string `json:"username"`
	Nickname    string `json:"nickname"`
	Status      string `json:"status"`
	GroupKey    string `json:"group_key"`
	Permissions []byte `json:"permissions"`
}

func (q *Queries) GetExternalIdentityUser(ctx context.Context, arg GetExternalIdentityUserParams) (GetExternalIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityUser, arg.ProviderID, arg.Subject)
	var i GetExternalIdentityUserRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Nickname,
		&i.Status,
		&i.GroupKey,
		&i.Permissions,
	)
	return i, err
}

const getOIDCProviderByID = `-- name: GetOIDCProviderByID :one
select id, key, display_name, issuer_url, client_id, client_secret_ciphertext, authorization_endpoint, token_endpoint, jwks_uri, allowed_email_domains, enabled, created_at, updated_at, deleted_at
from oidc_provider
where id = $1 and deleted_at is null
`

func (q *Queries) GetOIDCProviderByID(ctx context.Context, id pgtype.UUID) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProviderByID, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AuthorizationEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.AllowedEmailDomains,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEnabledOIDCProviders = `-- name: ListEnabledOIDCProviders :many
select key, display_name
from oidc_provider
where enabled and deleted_at is null
order by display_name, key
`

type ListEnabledOIDCProvidersRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListEnabledOIDCProviders(ctx context.Context) ([]ListEnabledOIDCProvidersRow, error) {
	rows, err := q.db.Query(ctx, listEnabledOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledOIDCProvidersRow{}
	for rows.Next() {
		var i ListEnabledOIDCProvidersRow
		if err := rows.Scan(&i.Key, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCProviders = `-- name: ListOIDCProviders :many
select id, key, display_name, issuer_url, client_id, client_secret_ciphertext, authorization_endpoint, token_endpoint, jwks_uri, allowed_email_domains, enabled, created_at, updated_at, deleted_at
from oidc_provider
where deleted_at is null
order by display_name, key
`

func (q *Queries) ListOIDCProviders(ctx context.Context) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, listOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcProvider{}
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecretCiphertext,
			&i.AuthorizationEndpoint,
			&i.TokenEndpoint,
			&i.JwksUri,
			&i.AllowedEmailDomains,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExternalIdentityKey = `-- name: LockExternalIdentityKey :exec
select pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockExternalIdentityKey(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockExternalIdentityKey, hashtextextended)
	return err
}

const softDeleteOIDCProvider = `-- name: SoftDeleteOIDCProvider :one
update oidc_provider
set enabled = false,
    deleted_at = clock_timestamp(),
    updated_at = clock_timestamp()
where id = $1
  and updated_at = $2
  and deleted_at is null
returning id, key, display_name, issuer_url, client_id, client_secret_ciphertext, authorization_endpoint, token_endpoint, jwks_uri, allowed_email_domains, enabled, created_at, updated_at, deleted_at
`

type SoftDeleteOIDCProviderParams struct {
	ID                pgtype.UUID        `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

func (q *Queries) SoftDeleteOIDCProvider(ctx context.Context, arg SoftDeleteOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, softDeleteOIDCProvider, arg.ID, arg.ExpectedUpdatedAt)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AuthorizationEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.AllowedEmailDomains,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const touchExternalIdentity = `-- name: TouchExternalIdentity :exec
update external_identity
set last_login_at = clock_timestamp()
where provider_id = $1 and subject = $2
`

type TouchExternalIdentityParams struct {
	ProviderID pgtype.UUID `json:"provider_id"`
	Subject    string      `json:"subject"`
}

func (q *Queries) TouchExternalIdentity(ctx context.Context, arg TouchExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, touchExternalIdentity, arg.ProviderID, arg.Subject)
	return err
}

const updateOIDCProvider = `-- name: UpdateOIDCProvider :one
update oidc_provider
set display_name = $1,
    issuer_url = $2,
    client_id = $3,
    client_secret_ciphertext = $4,
    authorization_endpoint = $5,
    token_endpoint = $6,
    jwks_uri = $7,
    allowed_email_domains = $8,
    enabled = $9,
    updated_at = clock_timestamp()
where id = $10
  and updated_at = $11
  and deleted_at is null
returning id, key, display_name, issuer_url, client_id, client_secret_ciphertext, authorization_endpoint, token_endpoint, jwks_uri, allowed_email_domains, enabled, created_at, updated_at, deleted_at
`

type UpdateOIDCProviderParams struct {
	DisplayName            string             `json:"display_name"`
	IssuerUrl              string             `json:"issuer_url"`
	ClientID               string             `json:"client_id"`
	ClientSecretCiphertext []byte             `json:"client_secret_ciphertext"`
	AuthorizationEndpoint  string             `json:"authorization_endpoint"`
	TokenEndpoint          string             `json:"token_endpoint"`
	JwksUri                string             `json:"jwks_uri"`
	AllowedEmailDomains    []byte             `json:"allowed_email_domains"`
	Enabled                bool               `json:"enabled"`
	ID                     pgtype.UUID        `json:"id"`
	ExpectedUpdatedAt      pgtype.Timestamptz `json:"expected_updated_at"`
}

func (q *Queries) UpdateOIDCProvider(ctx context.Context, arg UpdateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, updateOIDCProvider,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.AuthorizationEndpoint,
		arg.TokenEndpoint,
		arg.JwksUri,
		arg.AllowedEmailDomains,
		arg.Enabled,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AuthorizationEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.AllowedEmailDomains,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
