// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package sqlc

import (
	"context"
)

const getPermissionsByUsername = `-- name: GetPermissionsByUsername :one
select user_group.permissions
from app_user
join user_group on user_group.id = app_user.group_id
where app_user.username = $1 and app_user.deleted_at is null
`

func (q *Queries) GetPermissionsByUsername(ctx context.Context, username string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPermissionsByUsername, username)
	var permissions []byte
	err := row.Scan(&permissions)
	return permissions, err
}
