// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: short_link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllShortLinks = `-- name: CountAllShortLinks :one
select count(*)
from short_link
left join app_user on $1::text <> '' and app_user.id = short_link.owner_id
where short_link.deleted_at is null
    and ($2::text is null or short_link.status = $2::text)
    and (
        $1::text = ''
        or short_link.slug ilike '%' || $1::text || '%'
        or short_link.target_url ilike '%' || $1::text || '%'
        or app_user.username ilike '%' || $1::text || '%'
        or app_user.nickname ilike '%' || $1::text || '%'
    )
`

type CountAllShortLinksParams struct {
	Query  string      `json:"query"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) CountAllShortLinks(ctx context.Context, arg CountAllShortLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllShortLinks, arg.Query, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShortLinksByOwner = `-- name: CountShortLinksByOwner :one
select count(*)
from short_link
where owner_id = $1 and deleted_at is null
    and ($2::text is null or status = $2::text)
`

type CountShortLinksByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) CountShortLinksByOwner(ctx context.Context, arg CountShortLinksByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShortLinksByOwner, arg.OwnerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortLink = `-- name: CreateShortLink :one
insert into short_link (
    id, owner_id, domain_id, slug, target_url, status,
    redirect_mode, intermediate_delay_seconds, expires_at, password_hash,
    password_updated_at,
    created_at, updated_at
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, nullif($10::text, ''),
    case when coalesce($10::text, '') <> '' then clock_timestamp() else null end,
    now(), now())
returning id, owner_id, domain_id, slug, target_url, status,
    redirect_mode, intermediate_delay_seconds, expires_at,
    coalesce(expires_at <= clock_timestamp(), false)::boolean as expired,
    password_hash,
    created_at, updated_at, deleted_at
`

type CreateShortLinkParams struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
}

type CreateShortLinkRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	Expired                  bool               `json:"expired"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (CreateShortLinkRow, error) {
	row := q.db.QueryRow(ctx, createShortLink,
		arg.ID,
		arg.OwnerID,
		arg.DomainID,
		arg.Slug,
		arg.TargetUrl,
		arg.Status,
		arg.RedirectMode,
		arg.IntermediateDelaySeconds,
		arg.ExpiresAt,
		arg.PasswordHash,
	)
	var i CreateShortLinkRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.RedirectMode,
		&i.IntermediateDelaySeconds,
		&i.ExpiresAt,
		&i.Expired,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createShortLinkAccessGrant = `-- name: CreateShortLinkAccessGrant :one
insert into short_link_access_grant (id, short_link_id, token_hash, expires_at, created_at)
values ($1, $2, $3, $4, clock_timestamp())
returning id, short_link_id, token_hash, expires_at, created_at
`

type CreateShortLinkAccessGrantParams struct {
	ID          pgtype.UUID        `json:"id"`
	ShortLinkID pgtype.UUID        `json:"short_link_id"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateShortLinkAccessGrant(ctx context.Context, arg CreateShortLinkAccessGrantParams) (ShortLinkAccessGrant, error) {
	row := q.db.QueryRow(ctx, createShortLinkAccessGrant,
		arg.ID,
		arg.ShortLinkID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ShortLinkAccessGrant
	err := row.Scan(
		&i.ID,
		&i.ShortLinkID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredShortLinkAccessGrants = `-- name: DeleteExpiredShortLinkAccessGrants :execrows
with expired_grant as (
    select id
    from short_link_access_grant
    where expires_at <= clock_timestamp()
    order by expires_at
    limit $1::bigint
    for update skip locked
)
delete from short_link_access_grant as access_grant
using expired_grant
where access_grant.id = expired_grant.id
`

func (q *Queries) DeleteExpiredShortLinkAccessGrants(ctx context.Context, batchSize int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredShortLinkAccessGrants, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDatabaseTime = `-- name: GetDatabaseTime :one
select clock_timestamp()::timestamptz as database_time
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var database_time pgtype.Timestamptz
	err := row.Scan(&database_time)
	return database_time, err
}

const getShortLinkAnalyticsLink = `-- name: GetShortLinkAnalyticsLink :one
select short_link.id,
    short_link.owner_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    short_link.redirect_mode,
    short_link.intermediate_delay_seconds,
    short_link.expires_at,
    coalesce(short_link.expires_at <= clock_timestamp(), false)::boolean as expired,
    coalesce(short_link.password_hash, '') <> '' as has_password,
    short_link.created_at,
    domain.host as domain_host
from short_link
join domain on domain.id = short_link.domain_id
where short_link.id = $1 and short_link.deleted_at is null
`

type GetShortLinkAnalyticsLinkRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	Expired                  bool               `json:"expired"`
	HasPassword              bool               `json:"has_password"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	DomainHost               string             `json:"domain_host"`
}

func (q *Queries) GetShortLinkAnalyticsLink(ctx context.Context, id pgtype.UUID) (GetShortLinkAnalyticsLinkRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkAnalyticsLink, id)
	var i GetShortLinkAnalyticsLinkRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.RedirectMode,
		&i.IntermediateDelaySeconds,
		&i.ExpiresAt,
		&i.Expired,
		&i.HasPassword,
		&i.CreatedAt,
		&i.DomainHost,
	)
	return i, err
}

const getShortLinkBySlug = `-- name: GetShortLinkBySlug :one
select id, owner_id, domain_id, slug, target_url, status,
    redirect_mode, intermediate_delay_seconds, expires_at,
    coalesce(expires_at <= clock_timestamp(), false)::boolean as expired,
    password_hash,
    created_at, updated_at, deleted_at
from short_link
where slug = $1 and deleted_at is null
`

type GetShortLinkBySlugRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	Expired                  bool               `json:"expired"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetShortLinkBySlug(ctx context.Context, slug string) (GetShortLinkBySlugRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkBySlug, slug)
	var i GetShortLinkBySlugRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.RedirectMode,
		&i.IntermediateDelaySeconds,
		&i.ExpiresAt,
		&i.Expired,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShortLinkOverviewByOwner = `-- name: GetShortLinkOverviewByOwner :one
select count(distinct short_link.id)::bigint as total_link_count,
    count(distinct short_link.id) filter (where short_link.status = 'active')::bigint as active_link_count,
    count(short_link_event.id) filter (where short_link_event.event_type = 'redirect_response_sent')::bigint as visit_count,
    count(short_link_event.id) filter (
        where short_link_event.event_type = 'redirect_response_sent'
            and short_link_event.created_at >= current_date
            and short_link_event.created_at < current_date + interval '1 day'
    )::bigint as today_visit_count
from short_link
left join short_link_event on short_link_event.short_link_id = short_link.id
where short_link.owner_id = $1
    and short_link.deleted_at is null
`

type GetShortLinkOverviewByOwnerRow struct {
	TotalLinkCount  int64 `json:"total_link_count"`
	ActiveLinkCount int64 `json:"active_link_count"`
	VisitCount      int64 `json:"visit_count"`
	TodayVisitCount int64 `json:"today_visit_count"`
}

func (q *Queries) GetShortLinkOverviewByOwner(ctx context.Context, ownerID pgtype.UUID) (GetShortLinkOverviewByOwnerRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkOverviewByOwner, ownerID)
	var i GetShortLinkOverviewByOwnerRow
	err := row.Scan(
		&i.TotalLinkCount,
		&i.ActiveLinkCount,
		&i.VisitCount,
		&i.TodayVisitCount,
	)
	return i, err
}

const getShortLinkPasswordStateBySlugForUpdate = `-- name: GetShortLinkPasswordStateBySlugForUpdate :one
select id, password_hash, password_failed_attempts, password_window_started_at,
    password_blocked_until, password_updated_at
from short_link
where slug = $1 and deleted_at is null
for update
`

type GetShortLinkPasswordStateBySlugForUpdateRow struct {
	ID                      pgtype.UUID        `json:"id"`
	PasswordHash            pgtype.Text        `json:"password_hash"`
	PasswordFailedAttempts  int16              `json:"password_failed_attempts"`
	PasswordWindowStartedAt pgtype.Timestamptz `json:"password_window_started_at"`
	PasswordBlockedUntil    pgtype.Timestamptz `json:"password_blocked_until"`
	PasswordUpdatedAt       pgtype.Timestamptz `json:"password_updated_at"`
}

func (q *Queries) GetShortLinkPasswordStateBySlugForUpdate(ctx context.Context, slug string) (GetShortLinkPasswordStateBySlugForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkPasswordStateBySlugForUpdate, slug)
	var i GetShortLinkPasswordStateBySlugForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.PasswordFailedAttempts,
		&i.PasswordWindowStartedAt,
		&i.PasswordBlockedUntil,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const getShortLinkPasswordStateForUpdate = `-- name: GetShortLinkPasswordStateForUpdate :one
select id, password_hash, password_failed_attempts, password_window_started_at,
    password_blocked_until, password_updated_at
from short_link
where id = $1 and deleted_at is null
for update
`

type GetShortLinkPasswordStateForUpdateRow struct {
	ID                      pgtype.UUID        `json:"id"`
	PasswordHash            pgtype.Text        `json:"password_hash"`
	PasswordFailedAttempts  int16              `json:"password_failed_attempts"`
	PasswordWindowStartedAt pgtype.Timestamptz `json:"password_window_started_at"`
	PasswordBlockedUntil    pgtype.Timestamptz `json:"password_blocked_until"`
	PasswordUpdatedAt       pgtype.Timestamptz `json:"password_updated_at"`
}

func (q *Queries) GetShortLinkPasswordStateForUpdate(ctx context.Context, id pgtype.UUID) (GetShortLinkPasswordStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkPasswordStateForUpdate, id)
	var i GetShortLinkPasswordStateForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.PasswordFailedAttempts,
		&i.PasswordWindowStartedAt,
		&i.PasswordBlockedUntil,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const getValidShortLinkAccessGrant = `-- name: GetValidShortLinkAccessGrant :one
select access_grant.id, access_grant.short_link_id, access_grant.token_hash,
    access_grant.expires_at, access_grant.created_at
from short_link_access_grant as access_grant
join short_link on short_link.id = access_grant.short_link_id
where access_grant.short_link_id = $1
    and access_grant.token_hash = $2
    and access_grant.expires_at > clock_timestamp()
    and short_link.deleted_at is null
    and (short_link.password_updated_at is null or access_grant.created_at >= short_link.password_updated_at)
`

type GetValidShortLinkAccessGrantParams struct {
	ShortLinkID pgtype.UUID `json:"short_link_id"`
	TokenHash   string      `json:"token_hash"`
}

func (q *Queries) GetValidShortLinkAccessGrant(ctx context.Context, arg GetValidShortLinkAccessGrantParams) (ShortLinkAccessGrant, error) {
	row := q.db.QueryRow(ctx, getValidShortLinkAccessGrant, arg.ShortLinkID, arg.TokenHash)
	var i ShortLinkAccessGrant
	err := row.Scan(
		&i.ID,
		&i.ShortLinkID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllShortLinks = `-- name: ListAllShortLinks :many
select short_link.id,
    short_link.owner_id,
    short_link.domain_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    short_link.redirect_mode,
    short_link.intermediate_delay_seconds,
    short_link.expires_at,
    coalesce(short_link.expires_at <= clock_timestamp(), false)::boolean as expired,
    coalesce(short_link.password_hash, '') <> '' as has_password,
    short_link.created_at,
    short_link.updated_at,
    short_link.deleted_at,
    domain.host as domain_host,
    app_user.username as owner_username,
    app_user.nickname as owner_nickname,
    coalesce(stats.visit_count, 0)::bigint as visit_count,
    coalesce(stats.today_visit_count, 0)::bigint as today_visit_count,
    stats.last_visited_at::timestamptz as last_visited_at
from short_link
join domain on domain.id = short_link.domain_id
join app_user on app_user.id = short_link.owner_id
left join lateral (
    select count(*) filter (where event_type = 'redirect_response_sent')::bigint as visit_count,
        count(*) filter (where event_type = 'redirect_response_sent' and created_at >= current_date)::bigint as today_visit_count,
        max(created_at) filter (where event_type = 'redirect_response_sent') as last_visited_at
    from short_link_event
    where short_link_event.short_link_id = short_link.id
) stats on true
where short_link.deleted_at is null
    and ($3::text is null or short_link.status = $3::text)
    and (
        $4::text = ''
        or short_link.slug ilike '%' || $4::text || '%'
        or short_link.target_url ilike '%' || $4::text || '%'
        or app_user.username ilike '%' || $4::text || '%'
        or app_user.nickname ilike '%' || $4::text || '%'
    )
order by short_link.created_at desc
limit $1 offset $2
`

type ListAllShortLinksParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
	Query  string      `json:"query"`
}

type ListAllShortLinksRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	Expired                  bool               `json:"expired"`
	HasPassword              bool               `json:"has_password"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	DomainHost               string             `json:"domain_host"`
	OwnerUsername            string             `json:"owner_username"`
	OwnerNickname            string             `json:"owner_nickname"`
	VisitCount               int64              `json:"visit_count"`
	TodayVisitCount          int64              `json:"today_visit_count"`
	LastVisitedAt            pgtype.Timestamptz `json:"last_visited_at"`
}

func (q *Queries) ListAllShortLinks(ctx context.Context, arg ListAllShortLinksParams) ([]ListAllShortLinksRow, error) {
	rows, err := q.db.Query(ctx, listAllShortLinks,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllShortLinksRow{}
	for rows.Next() {
		var i ListAllShortLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.DomainID,
			&i.Slug,
			&i.TargetUrl,
			&i.Status,
			&i.RedirectMode,
			&i.IntermediateDelaySeconds,
			&i.ExpiresAt,
			&i.Expired,
			&i.HasPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DomainHost,
			&i.OwnerUsername,
			&i.OwnerNickname,
			&i.VisitCount,
			&i.TodayVisitCount,
			&i.LastVisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortLinksByOwner = `-- name: ListShortLinksByOwner :many
select short_link.id,
    short_link.owner_id,
    short_link.domain_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    short_link.redirect_mode,
    short_link.intermediate_delay_seconds,
    short_link.expires_at,
    coalesce(short_link.expires_at <= clock_timestamp(), false)::boolean as expired,
    coalesce(short_link.password_hash, '') <> '' as has_password,
    short_link.created_at,
    short_link.updated_at,
    short_link.deleted_at,
    domain.host as domain_host,
    coalesce(stats.visit_count, 0)::bigint as visit_count,
    coalesce(stats.today_visit_count, 0)::bigint as today_visit_count,
    stats.last_visited_at::timestamptz as last_visited_at
from short_link
join domain on domain.id = short_link.domain_id
left join lateral (
    select count(*) filter (where event_type = 'redirect_response_sent')::bigint as visit_count,
        count(*) filter (where event_type = 'redirect_response_sent' and created_at >= current_date)::bigint as today_visit_count,
        max(created_at) filter (where event_type = 'redirect_response_sent') as last_visited_at
    from short_link_event
    where short_link_event.short_link_id = short_link.id
) stats on true
where short_link.owner_id = $1 and short_link.deleted_at is null
    and ($4::text is null or short_link.status = $4::text)
order by short_link.created_at desc
limit $2 offset $3
`

type ListShortLinksByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Status  pgtype.Text `json:"status"`
}

type ListShortLinksByOwnerRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	Expired                  bool               `json:"expired"`
	HasPassword              bool               `json:"has_password"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	DomainHost               string             `json:"domain_host"`
	VisitCount               int64              `json:"visit_count"`
	TodayVisitCount          int64              `json:"today_visit_count"`
	LastVisitedAt            pgtype.Timestamptz `json:"last_visited_at"`
}

func (q *Queries) ListShortLinksByOwner(ctx context.Context, arg ListShortLinksByOwnerParams) ([]ListShortLinksByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listShortLinksByOwner,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortLinksByOwnerRow{}
	for rows.Next() {
		var i ListShortLinksByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.DomainID,
			&i.Slug,
			&i.TargetUrl,
			&i.Status,
			&i.RedirectMode,
			&i.IntermediateDelaySeconds,
			&i.ExpiresAt,
			&i.Expired,
			&i.HasPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DomainHost,
			&i.VisitCount,
			&i.TodayVisitCount,
			&i.LastVisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordShortLinkPasswordFailure = `-- name: RecordShortLinkPasswordFailure :exec
update short_link
set password_failed_attempts = $2,
    password_window_started_at = $3,
    password_blocked_until = $4
where id = $1 and deleted_at is null
`

type RecordShortLinkPasswordFailureParams struct {
	ID                      pgtype.UUID        `json:"id"`
	PasswordFailedAttempts  int16              `json:"password_failed_attempts"`
	PasswordWindowStartedAt pgtype.Timestamptz `json:"password_window_started_at"`
	PasswordBlockedUntil    pgtype.Timestamptz `json:"password_blocked_until"`
}

func (q *Queries) RecordShortLinkPasswordFailure(ctx context.Context, arg RecordShortLinkPasswordFailureParams) error {
	_, err := q.db.Exec(ctx, recordShortLinkPasswordFailure,
		arg.ID,
		arg.PasswordFailedAttempts,
		arg.PasswordWindowStartedAt,
		arg.PasswordBlockedUntil,
	)
	return err
}

const resetShortLinkPasswordFailures = `-- name: ResetShortLinkPasswordFailures :exec
update short_link
set password_failed_attempts = 0,
    password_window_started_at = null,
    password_blocked_until = null
where id = $1 and deleted_at is null
`

func (q *Queries) ResetShortLinkPasswordFailures(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetShortLinkPasswordFailures, id)
	return err
}

const softDeleteAnyShortLink = `-- name: SoftDeleteAnyShortLink :execrows
update short_link
set deleted_at = now(),
    updated_at = now()
where id = $1
    and deleted_at is null
`

func (q *Queries) SoftDeleteAnyShortLink(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAnyShortLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteOwnShortLink = `-- name: SoftDeleteOwnShortLink :execrows
update short_link
set deleted_at = now(),
    updated_at = now()
where id = $1
    and owner_id = $2
    and deleted_at is null
`

type SoftDeleteOwnShortLinkParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) SoftDeleteOwnShortLink(ctx context.Context, arg SoftDeleteOwnShortLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOwnShortLink, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnyShortLink = `-- name: UpdateAnyShortLink :one
with locked as materialized (
    select short_link.id,
        (
            $7::text = 'never'
            or ($7::text = 'set' and coalesce($8::text, '') <> '')
        ) as password_changed
    from short_link
    where short_link.id = $9
        and short_link.deleted_at is null
    for update
)
update short_link
set target_url = coalesce($1, target_url),
    status = coalesce($2, status),
    redirect_mode = coalesce($3::text, redirect_mode),
    intermediate_delay_seconds = coalesce($4::smallint, intermediate_delay_seconds),
    expires_at = case $5::text
        when 'never' then null
        when 'at' then $6::timestamptz
        else expires_at
    end,
    password_hash = case
        when $7::text = 'never' then null
        when locked.password_changed
            then $8::text
        else password_hash
    end,
    password_updated_at = case
        when locked.password_changed
            then clock_timestamp()
        else password_updated_at
    end,
    password_failed_attempts = case
        when locked.password_changed
            then 0
        else password_failed_attempts
    end,
    password_window_started_at = case
        when locked.password_changed
            then null
        else password_window_started_at
    end,
    password_blocked_until = case
        when locked.password_changed
            then null
        else password_blocked_until
    end,
    updated_at = now()
from locked
where short_link.id = locked.id
returning short_link.id, short_link.owner_id, short_link.domain_id, short_link.slug, short_link.target_url, short_link.status,
    short_link.redirect_mode, short_link.intermediate_delay_seconds, short_link.expires_at,
    coalesce(short_link.expires_at <= clock_timestamp(), false)::boolean as expired,
    short_link.password_hash, short_link.password_updated_at,
    short_link.created_at, short_link.updated_at, short_link.deleted_at
`

type UpdateAnyShortLinkParams struct {
	TargetUrl                pgtype.Text        `json:"target_url"`
	Status                   pgtype.Text        `json:"status"`
	RedirectMode             pgtype.Text        `json:"redirect_mode"`
	IntermediateDelaySeconds pgtype.Int2        `json:"intermediate_delay_seconds"`
	ExpirationMode           string             `json:"expiration_mode"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	PasswordMode             string             `json:"password_mode"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	ID                       pgtype.UUID        `json:"id"`
}

type UpdateAnyShortLinkRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	Expired                  bool               `json:"expired"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	PasswordUpdatedAt        pgtype.Timestamptz `json:"password_updated_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateAnyShortLink(ctx context.Context, arg UpdateAnyShortLinkParams) (UpdateAnyShortLinkRow, error) {
	row := q.db.QueryRow(ctx, updateAnyShortLink,
		arg.TargetUrl,
		arg.Status,
		arg.RedirectMode,
		arg.IntermediateDelaySeconds,
		arg.ExpirationMode,
		arg.ExpiresAt,
		arg.PasswordMode,
		arg.PasswordHash,
		arg.ID,
	)
	var i UpdateAnyShortLinkRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.RedirectMode,
		&i.IntermediateDelaySeconds,
		&i.ExpiresAt,
		&i.Expired,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOwnShortLink = `-- name: UpdateOwnShortLink :one
with locked as materialized (
    select short_link.id,
        (
            $7::text = 'never'
            or ($7::text = 'set' and coalesce($8::text, '') <> '')
        ) as password_changed
    from short_link
    where short_link.id = $9
        and short_link.owner_id = $10
        and short_link.deleted_at is null
    for update
)
update short_link
set target_url = coalesce($1, target_url),
    status = coalesce($2, status),
    redirect_mode = coalesce($3::text, redirect_mode),
    intermediate_delay_seconds = coalesce($4::smallint, intermediate_delay_seconds),
    expires_at = case $5::text
        when 'never' then null
        when 'at' then $6::timestamptz
        else expires_at
    end,
    password_hash = case
        when $7::text = 'never' then null
        when locked.password_changed
            then $8::text
        else password_hash
    end,
    password_updated_at = case
        when locked.password_changed
            then clock_timestamp()
        else password_updated_at
    end,
    password_failed_attempts = case
        when locked.password_changed
            then 0
        else password_failed_attempts
    end,
    password_window_started_at = case
        when locked.password_changed
            then null
        else password_window_started_at
    end,
    password_blocked_until = case
        when locked.password_changed
            then null
        else password_blocked_until
    end,
    updated_at = now()
from locked
where short_link.id = locked.id
returning short_link.id, short_link.owner_id, short_link.domain_id, short_link.slug, short_link.target_url, short_link.status,
    short_link.redirect_mode, short_link.intermediate_delay_seconds, short_link.expires_at,
    coalesce(short_link.expires_at <= clock_timestamp(), false)::boolean as expired,
    short_link.password_hash, short_link.password_updated_at,
    short_link.created_at, short_link.updated_at, short_link.deleted_at
`

type UpdateOwnShortLinkParams struct {
	TargetUrl                pgtype.Text        `json:"target_url"`
	Status                   pgtype.Text        `json:"status"`
	RedirectMode             pgtype.Text        `json:"redirect_mode"`
	IntermediateDelaySeconds pgtype.Int2        `json:"intermediate_delay_seconds"`
	ExpirationMode           string             `json:"expiration_mode"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	PasswordMode             string             `json:"password_mode"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
}

type UpdateOwnShortLinkRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	DomainID                 pgtype.UUID        `json:"domain_id"`
	Slug                     string             `json:"slug"`
	TargetUrl                string             `json:"target_url"`
	Status                   string             `json:"status"`
	RedirectMode             string             `json:"redirect_mode"`
	IntermediateDelaySeconds int16              `json:"intermediate_delay_seconds"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	Expired                  bool               `json:"expired"`
	PasswordHash             pgtype.Text        `json:"password_hash"`
	PasswordUpdatedAt        pgtype.Timestamptz `json:"password_updated_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateOwnShortLink(ctx context.Context, arg UpdateOwnShortLinkParams) (UpdateOwnShortLinkRow, error) {
	row := q.db.QueryRow(ctx, updateOwnShortLink,
		arg.TargetUrl,
		arg.Status,
		arg.RedirectMode,
		arg.IntermediateDelaySeconds,
		arg.ExpirationMode,
		arg.ExpiresAt,
		arg.PasswordMode,
		arg.PasswordHash,
		arg.ID,
		arg.OwnerID,
	)
	var i UpdateOwnShortLinkRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.RedirectMode,
		&i.IntermediateDelaySeconds,
		&i.ExpiresAt,
		&i.Expired,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
