// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: short_link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllShortLinks = `-- name: CountAllShortLinks :one
select count(*)
from short_link
left join app_user on $1::text <> '' and app_user.id = short_link.owner_id
where short_link.deleted_at is null
    and ($2::text is null or short_link.status = $2::text)
    and (
        $1::text = ''
        or short_link.slug ilike '%' || $1::text || '%'
        or short_link.target_url ilike '%' || $1::text || '%'
        or app_user.username ilike '%' || $1::text || '%'
        or app_user.nickname ilike '%' || $1::text || '%'
    )
`

type CountAllShortLinksParams struct {
	Query  string      `json:"query"`
	Status pgtype.Text `json:"status"`
}

// CountAllShortLinks returns the number of globally visible links matching filters.
func (q *Queries) CountAllShortLinks(ctx context.Context, arg CountAllShortLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllShortLinks, arg.Query, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShortLinksByOwner = `-- name: CountShortLinksByOwner :one
select count(*)
from short_link
where owner_id = $1 and deleted_at is null
    and ($2::text is null or status = $2::text)
`

type CountShortLinksByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Status  pgtype.Text `json:"status"`
}

// CountShortLinksByOwner returns the number of an owner's links matching filters.
func (q *Queries) CountShortLinksByOwner(ctx context.Context, arg CountShortLinksByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShortLinksByOwner, arg.OwnerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortLink = `-- name: CreateShortLink :one
insert into short_link (id, owner_id, domain_id, slug, target_url, status, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
returning id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
`

type CreateShortLinkParams struct {
	ID        pgtype.UUID `json:"id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	DomainID  pgtype.UUID `json:"domain_id"`
	Slug      string      `json:"slug"`
	TargetUrl string      `json:"target_url"`
	Status    string      `json:"status"`
}

// CreateShortLink inserts a short link and returns the stored row.
func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, createShortLink,
		arg.ID,
		arg.OwnerID,
		arg.DomainID,
		arg.Slug,
		arg.TargetUrl,
		arg.Status,
	)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShortLinkAnalyticsLink = `-- name: GetShortLinkAnalyticsLink :one
select short_link.id,
    short_link.owner_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    domain.host as domain_host
from short_link
join domain on domain.id = short_link.domain_id
where short_link.id = $1 and short_link.deleted_at is null
`

type GetShortLinkAnalyticsLinkRow struct {
	ID         pgtype.UUID `json:"id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Slug       string      `json:"slug"`
	TargetUrl  string      `json:"target_url"`
	Status     string      `json:"status"`
	DomainHost string      `json:"domain_host"`
}

// GetShortLinkAnalyticsLink returns the non-deleted link needed for analytics authorization and display.
func (q *Queries) GetShortLinkAnalyticsLink(ctx context.Context, id pgtype.UUID) (GetShortLinkAnalyticsLinkRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkAnalyticsLink, id)
	var i GetShortLinkAnalyticsLinkRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.DomainHost,
	)
	return i, err
}

const getShortLinkBySlug = `-- name: GetShortLinkBySlug :one
select id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
from short_link
where slug = $1 and deleted_at is null
`

// GetShortLinkBySlug returns a non-deleted short link by slug.
func (q *Queries) GetShortLinkBySlug(ctx context.Context, slug string) (ShortLink, error) {
	row := q.db.QueryRow(ctx, getShortLinkBySlug, slug)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllShortLinks = `-- name: ListAllShortLinks :many
select short_link.id,
    short_link.owner_id,
    short_link.domain_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    short_link.created_at,
    short_link.updated_at,
    short_link.deleted_at,
    domain.host as domain_host,
    app_user.username as owner_username,
    app_user.nickname as owner_nickname,
    coalesce(stats.visit_count, 0)::bigint as visit_count,
    coalesce(stats.today_visit_count, 0)::bigint as today_visit_count,
    stats.last_visited_at::timestamptz as last_visited_at
from short_link
join domain on domain.id = short_link.domain_id
join app_user on app_user.id = short_link.owner_id
left join lateral (
    select count(*) filter (where event_type = 'redirect_response_sent')::bigint as visit_count,
        count(*) filter (where event_type = 'redirect_response_sent' and created_at >= current_date)::bigint as today_visit_count,
        max(created_at) filter (where event_type = 'redirect_response_sent') as last_visited_at
    from short_link_event
    where short_link_event.short_link_id = short_link.id
) stats on true
where short_link.deleted_at is null
    and ($3::text is null or short_link.status = $3::text)
    and (
        $4::text = ''
        or short_link.slug ilike '%' || $4::text || '%'
        or short_link.target_url ilike '%' || $4::text || '%'
        or app_user.username ilike '%' || $4::text || '%'
        or app_user.nickname ilike '%' || $4::text || '%'
    )
order by short_link.created_at desc
limit $1 offset $2
`

type ListAllShortLinksParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
	Query  string      `json:"query"`
}

type ListAllShortLinksRow struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	DomainID        pgtype.UUID        `json:"domain_id"`
	Slug            string             `json:"slug"`
	TargetUrl       string             `json:"target_url"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DomainHost      string             `json:"domain_host"`
	OwnerUsername   string             `json:"owner_username"`
	OwnerNickname   string             `json:"owner_nickname"`
	VisitCount      int64              `json:"visit_count"`
	TodayVisitCount int64              `json:"today_visit_count"`
	LastVisitedAt   pgtype.Timestamptz `json:"last_visited_at"`
}

// ListAllShortLinks returns filtered global links with owner and visit statistics.
func (q *Queries) ListAllShortLinks(ctx context.Context, arg ListAllShortLinksParams) ([]ListAllShortLinksRow, error) {
	rows, err := q.db.Query(ctx, listAllShortLinks,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllShortLinksRow{}
	for rows.Next() {
		var i ListAllShortLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.DomainID,
			&i.Slug,
			&i.TargetUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DomainHost,
			&i.OwnerUsername,
			&i.OwnerNickname,
			&i.VisitCount,
			&i.TodayVisitCount,
			&i.LastVisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortLinksByOwner = `-- name: ListShortLinksByOwner :many
select short_link.id,
    short_link.owner_id,
    short_link.domain_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    short_link.created_at,
    short_link.updated_at,
    short_link.deleted_at,
    domain.host as domain_host,
    coalesce(stats.visit_count, 0)::bigint as visit_count,
    coalesce(stats.today_visit_count, 0)::bigint as today_visit_count,
    stats.last_visited_at::timestamptz as last_visited_at
from short_link
join domain on domain.id = short_link.domain_id
left join lateral (
    select count(*) filter (where event_type = 'redirect_response_sent')::bigint as visit_count,
        count(*) filter (where event_type = 'redirect_response_sent' and created_at >= current_date)::bigint as today_visit_count,
        max(created_at) filter (where event_type = 'redirect_response_sent') as last_visited_at
    from short_link_event
    where short_link_event.short_link_id = short_link.id
) stats on true
where short_link.owner_id = $1 and short_link.deleted_at is null
    and ($4::text is null or short_link.status = $4::text)
order by short_link.created_at desc
limit $2 offset $3
`

type ListShortLinksByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Status  pgtype.Text `json:"status"`
}

type ListShortLinksByOwnerRow struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	DomainID        pgtype.UUID        `json:"domain_id"`
	Slug            string             `json:"slug"`
	TargetUrl       string             `json:"target_url"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DomainHost      string             `json:"domain_host"`
	VisitCount      int64              `json:"visit_count"`
	TodayVisitCount int64              `json:"today_visit_count"`
	LastVisitedAt   pgtype.Timestamptz `json:"last_visited_at"`
}

// ListShortLinksByOwner returns an owner's links with visit statistics.
func (q *Queries) ListShortLinksByOwner(ctx context.Context, arg ListShortLinksByOwnerParams) ([]ListShortLinksByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listShortLinksByOwner,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortLinksByOwnerRow{}
	for rows.Next() {
		var i ListShortLinksByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.DomainID,
			&i.Slug,
			&i.TargetUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DomainHost,
			&i.VisitCount,
			&i.TodayVisitCount,
			&i.LastVisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAnyShortLink = `-- name: SoftDeleteAnyShortLink :execrows
update short_link
set deleted_at = now(),
    updated_at = now()
where id = $1
    and deleted_at is null
`

// SoftDeleteAnyShortLink marks a non-deleted link as deleted.
func (q *Queries) SoftDeleteAnyShortLink(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAnyShortLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteOwnShortLink = `-- name: SoftDeleteOwnShortLink :execrows
update short_link
set deleted_at = now(),
    updated_at = now()
where id = $1
    and owner_id = $2
    and deleted_at is null
`

type SoftDeleteOwnShortLinkParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// SoftDeleteOwnShortLink marks an owner's non-deleted link as deleted.
func (q *Queries) SoftDeleteOwnShortLink(ctx context.Context, arg SoftDeleteOwnShortLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOwnShortLink, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnyShortLink = `-- name: UpdateAnyShortLink :one
update short_link
set target_url = coalesce($1, target_url),
    status = coalesce($2, status),
    updated_at = now()
where id = $3
    and deleted_at is null
returning id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
`

type UpdateAnyShortLinkParams struct {
	TargetUrl pgtype.Text `json:"target_url"`
	Status    pgtype.Text `json:"status"`
	ID        pgtype.UUID `json:"id"`
}

// UpdateAnyShortLink updates a non-deleted link and returns the stored row.
func (q *Queries) UpdateAnyShortLink(ctx context.Context, arg UpdateAnyShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, updateAnyShortLink, arg.TargetUrl, arg.Status, arg.ID)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOwnShortLink = `-- name: UpdateOwnShortLink :one
update short_link
set target_url = coalesce($1, target_url),
    status = coalesce($2, status),
    updated_at = now()
where id = $3
    and owner_id = $4
    and deleted_at is null
returning id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
`

type UpdateOwnShortLinkParams struct {
	TargetUrl pgtype.Text `json:"target_url"`
	Status    pgtype.Text `json:"status"`
	ID        pgtype.UUID `json:"id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

// UpdateOwnShortLink updates an owner's non-deleted link and returns the stored row.
func (q *Queries) UpdateOwnShortLink(ctx context.Context, arg UpdateOwnShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, updateOwnShortLink,
		arg.TargetUrl,
		arg.Status,
		arg.ID,
		arg.OwnerID,
	)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
