// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: short_link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllShortLinks = `-- name: CountAllShortLinks :one
select count(*)
from short_link
join app_user on app_user.id = short_link.owner_id
where short_link.deleted_at is null
    and ($1::text = '' or short_link.status = $1::text)
    and (
        $2::text = ''
        or short_link.slug ilike '%' || $2::text || '%'
        or short_link.target_url ilike '%' || $2::text || '%'
        or app_user.username ilike '%' || $2::text || '%'
        or app_user.nickname ilike '%' || $2::text || '%'
    )
`

type CountAllShortLinksParams struct {
	Status string `json:"status"`
	Query  string `json:"query"`
}

func (q *Queries) CountAllShortLinks(ctx context.Context, arg CountAllShortLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllShortLinks, arg.Status, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShortLinksByOwner = `-- name: CountShortLinksByOwner :one
select count(*)
from short_link
where owner_id = $1 and deleted_at is null
    and ($2::text = '' or status = $2::text)
`

type CountShortLinksByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Status  string      `json:"status"`
}

func (q *Queries) CountShortLinksByOwner(ctx context.Context, arg CountShortLinksByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShortLinksByOwner, arg.OwnerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortLink = `-- name: CreateShortLink :one
insert into short_link (id, owner_id, domain_id, slug, target_url, status, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
returning id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
`

type CreateShortLinkParams struct {
	ID        pgtype.UUID `json:"id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	DomainID  pgtype.UUID `json:"domain_id"`
	Slug      string      `json:"slug"`
	TargetUrl string      `json:"target_url"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, createShortLink,
		arg.ID,
		arg.OwnerID,
		arg.DomainID,
		arg.Slug,
		arg.TargetUrl,
		arg.Status,
	)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShortLinkBySlug = `-- name: GetShortLinkBySlug :one
select id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
from short_link
where slug = $1 and deleted_at is null
`

func (q *Queries) GetShortLinkBySlug(ctx context.Context, slug string) (ShortLink, error) {
	row := q.db.QueryRow(ctx, getShortLinkBySlug, slug)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllShortLinks = `-- name: ListAllShortLinks :many
select short_link.id,
    short_link.owner_id,
    short_link.domain_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    short_link.created_at,
    short_link.updated_at,
    short_link.deleted_at,
    domain.host as domain_host,
    app_user.username as owner_username,
    app_user.nickname as owner_nickname
from short_link
join domain on domain.id = short_link.domain_id
join app_user on app_user.id = short_link.owner_id
where short_link.deleted_at is null
    and ($3::text = '' or short_link.status = $3::text)
    and (
        $4::text = ''
        or short_link.slug ilike '%' || $4::text || '%'
        or short_link.target_url ilike '%' || $4::text || '%'
        or app_user.username ilike '%' || $4::text || '%'
        or app_user.nickname ilike '%' || $4::text || '%'
    )
order by short_link.created_at desc
limit $1 offset $2
`

type ListAllShortLinksParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Status string `json:"status"`
	Query  string `json:"query"`
}

type ListAllShortLinksRow struct {
	ID            pgtype.UUID        `json:"id"`
	OwnerID       pgtype.UUID        `json:"owner_id"`
	DomainID      pgtype.UUID        `json:"domain_id"`
	Slug          string             `json:"slug"`
	TargetUrl     string             `json:"target_url"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DomainHost    string             `json:"domain_host"`
	OwnerUsername string             `json:"owner_username"`
	OwnerNickname string             `json:"owner_nickname"`
}

func (q *Queries) ListAllShortLinks(ctx context.Context, arg ListAllShortLinksParams) ([]ListAllShortLinksRow, error) {
	rows, err := q.db.Query(ctx, listAllShortLinks,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllShortLinksRow{}
	for rows.Next() {
		var i ListAllShortLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.DomainID,
			&i.Slug,
			&i.TargetUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DomainHost,
			&i.OwnerUsername,
			&i.OwnerNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortLinksByOwner = `-- name: ListShortLinksByOwner :many
select short_link.id,
    short_link.owner_id,
    short_link.domain_id,
    short_link.slug,
    short_link.target_url,
    short_link.status,
    short_link.created_at,
    short_link.updated_at,
    short_link.deleted_at,
    domain.host as domain_host
from short_link
join domain on domain.id = short_link.domain_id
where short_link.owner_id = $1 and short_link.deleted_at is null
    and ($4::text = '' or short_link.status = $4::text)
order by short_link.created_at desc
limit $2 offset $3
`

type ListShortLinksByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Status  string      `json:"status"`
}

type ListShortLinksByOwnerRow struct {
	ID         pgtype.UUID        `json:"id"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	DomainID   pgtype.UUID        `json:"domain_id"`
	Slug       string             `json:"slug"`
	TargetUrl  string             `json:"target_url"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	DomainHost string             `json:"domain_host"`
}

func (q *Queries) ListShortLinksByOwner(ctx context.Context, arg ListShortLinksByOwnerParams) ([]ListShortLinksByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listShortLinksByOwner,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortLinksByOwnerRow{}
	for rows.Next() {
		var i ListShortLinksByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.DomainID,
			&i.Slug,
			&i.TargetUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DomainHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAnyShortLink = `-- name: SoftDeleteAnyShortLink :execrows
update short_link
set deleted_at = now(),
    updated_at = now()
where id = $1
    and deleted_at is null
`

func (q *Queries) SoftDeleteAnyShortLink(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAnyShortLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteOwnShortLink = `-- name: SoftDeleteOwnShortLink :execrows
update short_link
set deleted_at = now(),
    updated_at = now()
where id = $1
    and owner_id = $2
    and deleted_at is null
`

type SoftDeleteOwnShortLinkParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) SoftDeleteOwnShortLink(ctx context.Context, arg SoftDeleteOwnShortLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOwnShortLink, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnyShortLink = `-- name: UpdateAnyShortLink :one
update short_link
set target_url = coalesce($1, target_url),
    status = coalesce($2, status),
    updated_at = now()
where id = $3
    and deleted_at is null
returning id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
`

type UpdateAnyShortLinkParams struct {
	TargetUrl pgtype.Text `json:"target_url"`
	Status    pgtype.Text `json:"status"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAnyShortLink(ctx context.Context, arg UpdateAnyShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, updateAnyShortLink, arg.TargetUrl, arg.Status, arg.ID)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOwnShortLink = `-- name: UpdateOwnShortLink :one
update short_link
set target_url = coalesce($1, target_url),
    status = coalesce($2, status),
    updated_at = now()
where id = $3
    and owner_id = $4
    and deleted_at is null
returning id, owner_id, domain_id, slug, target_url, status, created_at, updated_at, deleted_at
`

type UpdateOwnShortLinkParams struct {
	TargetUrl pgtype.Text `json:"target_url"`
	Status    pgtype.Text `json:"status"`
	ID        pgtype.UUID `json:"id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateOwnShortLink(ctx context.Context, arg UpdateOwnShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, updateOwnShortLink,
		arg.TargetUrl,
		arg.Status,
		arg.ID,
		arg.OwnerID,
	)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DomainID,
		&i.Slug,
		&i.TargetUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
