// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLoginMethodsSnapshot = `-- name: GetLoginMethodsSnapshot :one
select
    coalesce(
        (select value from system_setting where key = 'auth.local_login_enabled'),
        'true'::jsonb
    )::jsonb as local_login_enabled,
    coalesce(
        (select array_agg(key order by key) from oidc_provider where enabled and deleted_at is null),
        array[]::text[]
    )::text[] as provider_keys,
    coalesce(
        (select array_agg(display_name order by key) from oidc_provider where enabled and deleted_at is null),
        array[]::text[]
    )::text[] as provider_display_names
`

type GetLoginMethodsSnapshotRow struct {
	LocalLoginEnabled    []byte   `json:"local_login_enabled"`
	ProviderKeys         []string `json:"provider_keys"`
	ProviderDisplayNames []string `json:"provider_display_names"`
}

func (q *Queries) GetLoginMethodsSnapshot(ctx context.Context) (GetLoginMethodsSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getLoginMethodsSnapshot)
	var i GetLoginMethodsSnapshotRow
	err := row.Scan(&i.LocalLoginEnabled, &i.ProviderKeys, &i.ProviderDisplayNames)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
select key, value, created_at, updated_at
from system_setting
where key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemSettingForUpdate = `-- name: GetSystemSettingForUpdate :one
select key, value, created_at, updated_at
from system_setting
where key = $1
for update
`

func (q *Queries) GetSystemSettingForUpdate(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSettingForUpdate, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemSettings = `-- name: ListSystemSettings :many
select key, value, created_at, updated_at
from system_setting
where key = any($1::text[])
order by key
`

func (q *Queries) ListSystemSettings(ctx context.Context, dollar_1 []string) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystemSettingValue = `-- name: UpdateSystemSettingValue :one
update system_setting
set value = $2,
    updated_at = $3
where key = $1
returning key, value, created_at, updated_at
`

type UpdateSystemSettingValueParams struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSystemSettingValue(ctx context.Context, arg UpdateSystemSettingValueParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, updateSystemSettingValue, arg.Key, arg.Value, arg.UpdatedAt)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
insert into system_setting (key, value, created_at, updated_at)
values ($1, $2, now(), now())
on conflict (key) do update
set value = excluded.value,
    updated_at = now()
returning key, value, created_at, updated_at
`

type UpsertSystemSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
