// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system.sql

package sqlc

import (
	"context"
)

const getSystemSetting = `-- name: GetSystemSetting :one
select key, value, created_at, updated_at
from system_setting
where key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
insert into system_setting (key, value, created_at, updated_at)
values ($1, $2, now(), now())
on conflict (key) do update
set value = excluded.value,
    updated_at = now()
returning key, value, created_at, updated_at
`

type UpsertSystemSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
