// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppUser = `-- name: CreateAppUser :one
insert into app_user (id, username, password_hash, nickname, group_id, status, builtin, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, $7, now(), now())
returning id, username, password_hash, nickname, group_id, status, builtin, created_at, updated_at, deleted_at
`

type CreateAppUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Nickname     string      `json:"nickname"`
	GroupID      pgtype.UUID `json:"group_id"`
	Status       string      `json:"status"`
	Builtin      bool        `json:"builtin"`
}

func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Nickname,
		arg.GroupID,
		arg.Status,
		arg.Builtin,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.GroupID,
		&i.Status,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserGroup = `-- name: CreateUserGroup :one
insert into user_group (id, key, name, description, permissions, builtin, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
returning id, key, name, description, permissions, builtin, created_at, updated_at
`

type CreateUserGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	Key         string      `json:"key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Permissions []byte      `json:"permissions"`
	Builtin     bool        `json:"builtin"`
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createUserGroup,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.Builtin,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, password_hash, nickname, group_id, status, builtin, created_at, updated_at, deleted_at
from app_user
where username = $1 and deleted_at is null
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.GroupID,
		&i.Status,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserGroupByKey = `-- name: GetUserGroupByKey :one
select id, key, name, description, permissions, builtin, created_at, updated_at
from user_group
where key = $1
`

func (q *Queries) GetUserGroupByKey(ctx context.Context, key string) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getUserGroupByKey, key)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
